apiVersion: v1
kind: Service
metadata:
  name: github-private-repo-files-service
  namespace: github-private-repo
  labels:
    run: github-private-repo-files
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: port-5000
    targetPort: 5000
  selector:
    run: github-private-repo-files
  type: ClusterIP